
import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import PageSelector from './components/PageSelector';
import './globals.css'

import '@fortawesome/fontawesome-svg-core/styles.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'UtilGPT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="bg-slate-50 border-b-2">
            <div className='flex m-auto container justify-between  items-center p-4 gap-4 h-16  text-black'>
              <div>
                <a href="/" className="text-2xl font-bold ">
                  UtilGPT
                </a>
                {/* Page selector client component */}
                <PageSelector />
              </div>

              <div className='flex items-center gap-4'>
                <SignedOut>
                  <SignInButton>
                    <button className="rounded-sm font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign In
                    </button>
                  </SignInButton>
                  <SignUpButton>
                    <button className="bg-amber-600 rounded-sm font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </div>


          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}