
import { type Metadata } from 'next'
import {
  ClerkProvider
} from '@clerk/nextjs'
import AuthButtons from './components/AuthButtons';
import { Geist, Geist_Mono } from 'next/font/google'
import PageSelector from './components/PageSelector';
import './globals.css'

import '@fortawesome/fontawesome-svg-core/styles.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'UtilGPT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="bg-slate-50 border-b-2">
            <div className='flex m-auto container justify-between items-center p-4 gap-4 h-16 text-black fixed top-0 left-0 right-0 z-50 bg-slate-50 border-b-2'>
              <div>
                <a href="/" className="text-2xl font-bold ">
                  UtilGPT
                </a>
                {/* Page selector client component */}

              </div>

              <div className='flex items-center gap-4'>
                <AuthButtons />
              </div>
            </div>


          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}